### ISSUE TITLE
安卓 添加网络请求后 报错

### ISSUE THREAD

**Issue by ChrisWuAnHui** [janiokq/react-native-nlist#1]
刷新和加载数据的时候，使用网络数据。渲染报错
![d4e87c1f7395589e94c1f80745026217](https://user-images.githubusercontent.com/17464713/48885384-0f42a900-ee63-11e8-8704-6ccd27f2c2cf.jpg)
![d952288f51169bd6927a1e69995f01ec](https://user-images.githubusercontent.com/17464713/48885392-12d63000-ee63-11e8-99fd-d27eb82e50ca.jpg)
![3dd1bbc9cd8939e8f0062900fefe3b01](https://user-images.githubusercontent.com/17464713/48885395-15388a00-ee63-11e8-8e32-7ca774725242.jpg)

**Comment by janiokq** [comment]
Item must have high attributes

**Comment by janiokq** [comment]
数据集里面的对象必须要有 高度属性 item的 高度声明

**Comment by ChrisWuAnHui** [comment]
意思是每条数据手动在添加一条height属性？
![image](https://user-images.githubusercontent.com/17464713/48888666-61d59280-ee6e-11e8-8c5e-c03a88be083f.png)

**Comment by janiokq** [comment]
![image](https://user-images.githubusercontent.com/10770735/48888694-79148000-ee6e-11e8-9373-adef9a8fac16.png)
![image](https://user-images.githubusercontent.com/10770735/48888714-8a5d8c80-ee6e-11e8-8523-e34dfbcc8d15.png)

是的因为itme的 高度 原生不能 自动 计算 这里  要 指定   
rn的渲染机制导致无法测量 item 高度  因为他的渲染和 原生线程不同步

Yes, because the height of itme is not naturally computed automatically, which is specified here.

Rn's rendering mechanism makes it impossible to measure item height because its rendering is not synchronized with native threads

**Comment by lhh-sofy** [comment]
> ![image](https://user-images.githubusercontent.com/10770735/48888694-79148000-ee6e-11e8-9373-adef9a8fac16.png)
> ![image](https://user-images.githubusercontent.com/10770735/48888714-8a5d8c80-ee6e-11e8-8523-e34dfbcc8d15.png)
> 
> 是的因为itme的 高度 原生不能 自动 计算 这里 要 指定
> rn的渲染机制导致无法测量 item 高度 因为他的渲染和 原生线程不同步
> 
> Yes, because the height of itme is not naturally computed automatically, which is specified here.
> 
> Rn's rendering mechanism makes it impossible to measure item height because its rendering is not synchronized with native threads
但是列表中的高度大部分时间是不固定的，也没办法进行计算的，比如头条的文章列表。

**Comment by lhh-sofy** [comment]
这样就有问题了啊，大部分时间，列表的每个item是不固定的，比如头条的文章列表样式。
